name: 'Gitbook Build'
on:
  push:
    branches:
      - maain
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v2
    - name: Gitbook Action                          # https://github.com/ZanderZhao/gitbook-action/releases
      uses: ZanderZhao/gitbook-action@v1.2.4        # -> or ZanderZhao/gitbook-action@master.  If not use master click above, use latest please 
      with:                                         #    or fork this repo and use YourName/gitbook-action@master
        token: ${{ secrets.GITBOOK_ACTION_TOKEN }}  # -> remember add this in settings/secrets
        source_branch: main
        #source_dir: docs-src
        #source_edit_time: true
        #publish_commit_message: ${{ github.event.head_commit.message }}
        #publish_branch: gh-pages
        #publish_dir: docs
        font_install: sudo apt-get install ttf-mscorefonts-installer
        gitbook_pdf: true
        #gitbook_pdf_dir: downloads
        gitbook_pdf_name: book-name
